### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by nmdoshi** [KevinFasusi/supplychainpy#52]
I am trying to install the supplychainpy library and I get the following error. 
pip install supplychainpy
Collecting supplychainpy
  Using cached supplychainpy-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l9/v14kxshd471dfpths33p4snr0000gn/T/pip-build-kuh2s2bo/supplychainpy/setup.py", line 10, in <module>
        f = open(os.path.join(here,'LOG.txt'))
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/l9/v14kxshd471dfpths33p4snr0000gn/T/pip-build-kuh2s2bo/supplychainpy/LOG.txt'
    
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l9/v14kxshd471dfpths33p4snr0000gn/T/pip-build-kuh2s2bo/supplychainpy/

**Comment by KevinFasusi** [comment]
Hi @nmdoshi,

Thank you for posting this issue. A file used when uploading to PyPi, used by`setup.py` (LOG.txt), was not present in the `supplychainpy-0.0.4.tar.gz`. I am not sure how this happened, considering that it is present in the compressed file for release 0.0.4 on GitHub.

I am currently going through the release process for 0.0.5. In the interim, I have pushed a release candidate to PyPi. Please use:

`$ pip install supplychainpy==0.0.5rc0`

I have tested the 'pip' command my local Linux box, and the bug you posted is not present anymore. Please let me know if you have any trouble.

**Comment by nmdoshi** [comment]
thanks Kevin, I will give this a try

**Comment by nmdoshi** [comment]
This works, I was able to install it successfully
