### ISSUE TITLE
Python 3.5 cannot install supplychainpy

### ISSUE THREAD

**Issue by zenz** [KevinFasusi/supplychainpy#64]
tried pip install supplychainpy
and also clone git repo and python3 setup.py install.
Got this error: can't copy 'supplychainpy/reporting/static': doesn't exist or not a regular file

**Comment by KevinFasusi** [comment]
Hi @zenz,

 What OS are you using and do you use a virtual environment like Virtualenv or pyenv?

**Comment by zenz** [comment]
@KevinFasusi OS: Ubuntu Linux 16.04 with virtual environment.

**Comment by KevinFasusi** [comment]
Hi @zenz,

I tested pip install on an Ubuntu Linux 16.04 box using Anaconda (conda -create testenv python=3.5) and with virtualenv and the installation completes without errors. I also installed from source and did not get this error.

Did you get the error when you ran pip or when you tried to install from source? Also, please can you copy and paste the full error?

If possible, and you have not done so already, could you try creating a separate environment for the project and try pip install again?

Another option may be to try a different virtual environment tool like Anaconda. 

Alternatively, if you are testing the project, you might be interested in the docker version (supplychainpy/suchpy:0.0.5). This option avoids some of the issues related to the state or configuration of your system. The image is a big one, but it comes with all the usual packages, as it built from an Anaconda image.

**Comment by zenz** [comment]
@KevinFasusi I can install 0.0.3 and 0.0.4 without any problem, only 0.0.5 not work. there's no more detail log from the pip report or install from source.

**Comment by KevinFasusi** [comment]
@zenz Okay, Thank you. I will continue looking into the issue.

**Comment by zenz** [comment]
@KevinFasusi 
I solve the install problem by cmd: pip3 install --upgrade setuptools
so may be this issue can be close now. and may I suggest to add this to the installation document.

**Comment by KevinFasusi** [comment]
@zenz 
Thanks for the update, glad you solved the issue. I will add a note to the docs, under a troubleshooting section, for the next release.

**Comment by kumar781** [comment]
I tried 'pip3 install --upgrade setuptools' and then 'pip install supplychainpy' on jupyter notebook (windows 10 64 bit).
The notebook basically freezes. Could anyone help me on this?

**Comment by zenz** [comment]
@kumar781 which version of python are you using? do you install cython? supplychainpy current without updated must modify a lot to be compile under python3.7.

**Comment by KevinFasusi** [comment]
@zenz  Thank you for replying to issues on this project. I really appreciate you taking the time to respond.

**Comment by zenz** [comment]
@KevinFasusi Supplychainpy is a powerful and handy tool fit for my work, So I would like to assist the others to use it if I can. :)
