### ISSUE TITLE
Python 3.7 cannot install suppplychainpy

### ISSUE THREAD

**Issue by KiranKumar-A** [KevinFasusi/supplychainpy#70]
Hi Kevin,
I am not able to install supplychainpy=0.0.5.

Getting error like failed to build wheel file.

**Comment by tmo2021** [comment]
install from command line and use "git+https://github.com/KevinFasusi/supplychainpy" thats what I had trouble with but I figured it out.

**Comment by zenz** [comment]
you need to use ipython to recompile all the pyx files first

**Comment by KiranKumar-A** [comment]
Thank you
